[package]
name = "creft"
version = "0.1.0"
edition = "2021"

[dependencies]
pemel = "0.2.0"
poise = "0.6.1"
shuttle-runtime = "0.52.0"
shuttle-serenity = "0.52.0"
shuttle-shared-db = { version = "0.52.0", features = ["postgres", "sqlx"] }
sqlx = "0.8.2"
tokio = "1.26.0"
tracing = "0.1.37"
